### ISSUE TITLE
copy and paste with indentation

### ISSUE THREAD

**Issue by e-carlin** [biviosoftware/home-env#79]
Indentation gets messed up when I copy and paste (through OS clipboard) into an emacs buffer. For example, copy the following and paste into `*scratch*`. 

```
      devbox:
        docker_image: radiasoft/sirepo-devbox:alpha
        guest_d: /some/dir
        ssh_service_port_difference: 1
        users:
          userA: 8888
```

I get
```
devbox:
docker_image: radiasoft/sirepo-devbox:alpha
guest_d: /some/dir
ssh_service_port_difference: 1
users:
          userA: 8888
```

Does this happen to anyone else? Does anyone have a workaround?
